/**
 * Encrypt the members-only calendar data into a static, password-protected
 * payload the browser can decrypt with the Web Crypto API.
 *
 * Source (plaintext, gitignored):  members-src/calendar-data.json
 * Output (ciphertext, committed):  js/members-data.js
 *
 * Crypto: PBKDF2(SHA-256, 250k iters) -> AES-256-GCM. The output format
 * matches what js/members.js expects and what the browser's SubtleCrypto
 * produces, so encrypt here / decrypt there interoperate exactly.
 *
 * Usage (pick your own password — never commit or share it):
 *   STW_MEMBERS_PASSWORD="your-password" node tools/encrypt-members.mjs
 *   # PowerShell:
 *   $env:STW_MEMBERS_PASSWORD="your-password"; node tools/encrypt-members.mjs
 */
import crypto from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "members-src", "calendar-data.json");
const OUT = join(ROOT, "js", "members-data.js");

const ITERATIONS = 250000;

const password = process.env.STW_MEMBERS_PASSWORD || process.argv[2];
if (!password) {
  console.error(
    "Missing password. Set STW_MEMBERS_PASSWORD or pass it as the first argument."
  );
  process.exit(1);
}

// Validate the source is real JSON before encrypting.
const plaintext = readFileSync(SRC, "utf8");
JSON.parse(plaintext);

const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const key = crypto.pbkdf2Sync(password, salt, ITERATIONS, 32, "sha256");

const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
const enc = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
const tag = cipher.getAuthTag();
const ct = Buffer.concat([enc, tag]); // GCM tag appended, as Web Crypto expects

const payload = {
  v: 1,
  kdf: { name: "PBKDF2", hash: "SHA-256", iterations: ITERATIONS },
  salt: salt.toString("base64"),
  iv: iv.toString("base64"),
  ct: ct.toString("base64")
};

const banner =
  "/* AUTO-GENERATED by tools/encrypt-members.mjs — do not edit by hand.\n" +
  "   Encrypted with a password you control. Re-run the script to update. */\n";

writeFileSync(
  OUT,
  banner + "window.__STW_MEMBERS__ = " + JSON.stringify(payload) + ";\n",
  "utf8"
);

console.log("Encrypted " + SRC);
console.log("Wrote     " + OUT);
console.log("Events:   recurring + annual encrypted under your password.");
